<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-Q4BPVH9" ignored="0" name="Default test" tests="5" failures="1" timestamp="15 Oct 2019 10:04:38 GMT" time="0.043" errors="0">
  <testcase name="@AfterTest logout" time="0.003" classname="com.euscold.db_data_comparision_with_ui.Inventory_Inquiry_Multiple_Prods">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.euscold.db_data_comparision_with_ui.Inventory_Inquiry_Multiple_Prods.logout(Inventory_Inquiry_Multiple_Prods.java:494)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.TestRunner.afterRun(TestRunner.java:725)
at org.testng.TestRunner.run(TestRunner.java:509)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- @AfterTest logout -->
  <testcase name="excelCreation" time="0.005" classname="com.euscold.db_data_comparision_with_ui.Inventory_Inquiry_Multiple_Prods">
    <failure type="java.io.FileNotFoundException" message="D:\Workspace\eUSCOLD\src\test\resources\testresults\Inventory_Inquiry_Prod.xls (The process cannot access the file because it is being used by another process)">
      <![CDATA[java.io.FileNotFoundException: D:\Workspace\eUSCOLD\src\test\resources\testresults\Inventory_Inquiry_Prod.xls (The process cannot access the file because it is being used by another process)
at java.io.FileOutputStream.open0(Native Method)
at java.io.FileOutputStream.open(FileOutputStream.java:270)
at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
at com.euscold.db_data_comparision_with_ui.Inventory_Inquiry_Multiple_Prods.excelCreation(Inventory_Inquiry_Multiple_Prods.java:42)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- excelCreation -->
  <testcase name="Inv_Query" time="0.0" classname="com.euscold.db_data_comparision_with_ui.Inventory_Inquiry_Multiple_Prods">
    <skipped/>
  </testcase> <!-- Inv_Query -->
  <testcase name="eUSCOLD_Login" time="0.0" classname="com.euscold.db_data_comparision_with_ui.Inventory_Inquiry_Multiple_Prods">
    <skipped/>
  </testcase> <!-- eUSCOLD_Login -->
  <testcase name="Inventory" time="0.0" classname="com.euscold.db_data_comparision_with_ui.Inventory_Inquiry_Multiple_Prods">
    <skipped/>
  </testcase> <!-- Inventory -->
  <testcase name="prod" time="0.0" classname="com.euscold.db_data_comparision_with_ui.Inventory_Inquiry_Multiple_Prods">
    <skipped/>
  </testcase> <!-- prod -->
</testsuite> <!-- Default test -->
